---

- name: 安装keepalived
  yum:
    name: keepalived
    state: present

- name: 下发keepalived master配置文件
  template: 
    src: keepalived-master.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - 重新启动keepalived服务
  when: 'inventory_hostname == groups.lb[0]'

- name: 下发keepalived backup配置文件
  template: 
    src: keepalived-backup.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - 重新启动keepalived服务
  when: 'inventory_hostname == groups.lb[1]'
