#
# Ansible Inventory File
#

[master]
master1.localdomain ansible_host=192.168.0.150
master2.localdomain ansible_host=192.168.0.151
master3.localdomain ansible_host=192.168.0.152

[master:vars]
# k8s 各组件数据目录
k8s_dir=/data/k8s/k8s
# 服务网段，部署前路由不可达，部署后集群内路由可达(kube-proxy 保证)
service_cidr=10.254.0.0/16
# kube-apiserver VIP 地址（HA 组件 haproxy 监听 8443 端口）
# kube_apiserver=https://192.168.0.149:8443
# k8s日志目录
k8s_log_dir=/var/log/kubernetes


[worker]
node1.localdomain ansible_host=192.168.0.153
node2.localdomain ansible_host=192.168.0.154
node3.localdomain ansible_host=192.168.0.155

[worker:vars]
# docker 目录
docker_dir=/data/k8s/docker

# docker 数据目录
docker_data_dir=/data/k8s/docker/data

# registry-mirrors
registry_mirrors="https://c54hhh4b.mirror.aliyuncs.com"

# insecure-registries. docker group
insecure_registries="192.168.0.120:8083"

# k8s 各组件数据目录
k8s_dir=/data/k8s/k8s
# k8s日志目录
k8s_log_dir=/var/log/kubernetes
# kube-apiserver VIP 地址（HA 组件 haproxy 监听 8443 端口）
kube_apiserver=https://192.168.0.150:8443


[k8s_cluster:children]
master
worker

[k8s_cluster:vars]
# nexus 地址
nexus_ip=192.168.0.120 

# nexus centos源代理地址
nexus_base_url=http://192.168.0.120:8081/repository/centos/

# nexus epel源代理地址
nexus_epel_url=http://192.168.0.120:8081/repository/epel/

# nexus python源代理地址
nexus_python_url=http://192.168.0.120:8081/repository/python-proxy/

# nexus docker源代理地址
nexus_docker_url=http://192.168.0.120:8081/repository/docker-ce/

# k8s-deploy目录所在目录
k8s_deploy_path=/root/k8s-deploy

# bin文件中对应的k8s版本
k8s_version=1.15.11

# kube-apiserver 的 VIP（HA 组件 keepalived 发布的 IP）
master_vip=192.168.0.149
# kube-apiserver VIP 地址（HA 组件 haproxy 监听 8443 端口）
# kube_apiserver=https://192.168.0.149:8443


[etcd]
192.168.0.150 ansible_host=192.168.0.150 node_name=etcd1
192.168.0.151 ansible_host=192.168.0.151 node_name=etcd2
192.168.0.152 ansible_host=192.168.0.152 node_name=etcd3

[etcd:vars]
# etcd工作目录
etcd_work_dir=/var/lib/etcd

# etcd数据目录
etcd_data_dir=/data/k8s/etcd/data

# etcd WAL目录
etcd_wal_dir=/data/k8s/etcd/wal

[lb]
#运行 keepalived 和 haproxy 的节点称为 LB 节点。由于 keepalived 是一主多备运行模式，故至少两个 LB 节点。
master2.localdomain ansible_host=192.168.0.151 priority=100
master3.localdomain ansible_host=192.168.0.152 priority=90


[lb:vars]
lb_iface=eth0
master_vip=192.168.0.149







