#
# Ansible Inventory File
#

[master]
master1.localdomain ansible_host=192.168.0.150
master2.localdomain ansible_host=192.168.0.151
master3.localdomain ansible_host=192.168.0.152

[worker]
node1.localdomain ansible_host=192.168.0.153
node2.localdomain ansible_host=192.168.0.154
node3.localdomain ansible_host=192.168.0.155

[worker:vars]
# docker 目录
docker_dir=/data/k8s/docker

# docker 数据目录
docker_data_dir=/data/k8s/docker/data

# docker 运行目录
docker_exec_dir=/data/k8s/docker/exec

# registry-mirrors
registry_mirrors="https://c54hhh4b.mirror.aliyuncs.com"

# insecure-registries
insecure_registries="192.168.0.120:8082"


[k8s_cluster:children]
master
worker

[k8s_cluster:vars]
# nexus centos源代理地址
nexus_base_url=http://192.168.0.120:8081/repository/centos/

# nexus epel源代理地址
nexus_epel_url=http://192.168.0.120:8081/repository/epel/

# k8s-deploy目录所在目录
k8s_deploy_path=/root/k8s-deploy

# bin文件中对应的k8s版本
k8s_version=1.16.6

# k8s api-server地址
k8s_api_server=master1.localdomain


[etcd]
192.168.0.150 ansible_host=192.168.0.150 node_name=etcd1
192.168.0.151 ansible_host=192.168.0.151 node_name=etcd2
192.168.0.152 ansible_host=192.168.0.152 node_name=etcd3

[etcd:vars]
# etcd工作目录
etcd_work_dir=/var/lib/etcd

# etcd数据目录
etcd_data_dir=/data/k8s/etcd/data

# etcd WAL目录
etcd_wal_dir=/data/k8s/etcd/wal





