---

- name: 创建目录
  file:
    path: "{{ k8s_dir }}/kube-controller-manager"
    state: directory

- name: 生成证书
  shell: "/opt/k8s/bin/cfssl gencert -ca=/opt/k8s/work/ca.pem -ca-key=/opt/k8s/work/ca-key.pem -config=/opt/k8s/work/ca-config.json -profile=kubernetes kube-controller-manager-csr.json | /opt/k8s/bin/cfssljson -bare kube-controller-manager"
  args:
    chdir: /opt/k8s/work/
    creates: kube-controller-manager.pem
#  ignore_errors: true
  when: 'inventory_hostname == groups.master[0]'

- name: 分发生成的证书和私钥
  copy:
    src: "/opt/k8s/work/{{ item }}"
    dest: "/etc/kubernetes/cert/{{ item }}"
  with_list:
    - kube-controller-manager.pem
    - kube-controller-manager-key.pem
  notify:
    - 重新启动kube-controller-manager.service服务

- name: 生成kube-controller-manager.kubeconfig文件 - 1
  shell: "/opt/k8s/bin/kubectl config set-cluster kubernetes --certificate-authority=/opt/k8s/work/ca.pem --server={{ kube_apiserver }} --kubeconfig=kube-controller-manager.kubeconfig"
  args:
    chdir: /opt/k8s/work/
  when: 'inventory_hostname == groups.master[0]'

- name: 生成kube-controller-manager.kubeconfig文件 - 2
  shell: "/opt/k8s/bin/kubectl config set-credentials system:kube-controller-manager --client-certificate=/opt/k8s/work/kube-controller-manager.pem --client-key=/opt/k8s/work/kube-controller-manager-key.pem --kubeconfig=kube-controller-manager.kubeconfig"
  args:
    chdir: /opt/k8s/work/
  when: 'inventory_hostname == groups.master[0]'

- name: 生成kube-controller-manager.kubeconfig文件 - 3
  shell: "/opt/k8s/bin/kubectl config set-context system:kube-controller-manager --cluster=kubernetes --user=system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig"
  args:
    chdir: /opt/k8s/work/
  when: 'inventory_hostname == groups.master[0]'

- name: 设置默认上下文
  shell: "/opt/k8s/bin/kubectl config use-context system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig"
  args:
    chdir: /opt/k8s/work/

- name: 分发 kube-controller-manager.kubeconfig 文件
  copy:
    src: "/opt/k8s/work/kube-controller-manager.kubeconfig"
    dest: /etc/kubernetes/kube-controller-manager.kubeconfig

- name: 分发kube-controller-manager.service文件
  template: 
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  notify:
    - 重新启动kube-controller-manager.service服务


