---
- name: Set variable with SSL/TLS to enabled false
  set_fact: is_ssl_enabled="false"
  changed_when: false

- name: Check if variable with SSL/TLS should be set to true
  set_fact: is_ssl_enabled="{{ rabbitmq.custom_configurations | selectattr('name','equalto','listeners.ssl.default') | list | length > 0 }}"
  changed_when: false
  when: rabbitmq.custom_configurations | length > 0

- name: rabbitmq default file
  template:
    src: rabbitmq-conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: root
    group: root
    mode: 0644
  register: config_changed

- name: default settings for RabbitMQ AMQP server
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: root
    group: root
    mode: 0644
  register: env_settings_changed

- name: Symlink RabbitMQ bin to sbin(for install plugins)
  file:
    src: /usr/lib/rabbitmq/bin
    dest: /usr/lib/rabbitmq/sbin
    state: link

- name: Enable plugins that were installed
  rabbitmq_plugin:
    names: "{{ item }}"
    prefix: /usr/lib/rabbitmq
    state: enabled
    new_only: no
  with_items: "{{ rabbitmq.plugins }}"

- name: Restart RabbitMQ
  systemd: 
    name: rabbitmq-server
    state: restarted
  when:
    - config_changed.changed or env_settings_changed.changed
    - not is_ssl_enabled

- name: Stop RabbitMQ for manual certificates configuration
  service: name=rabbitmq-server state=stopped
  when:
     - is_ssl_enabled