---
- import_tasks: "cookie-setup/master.yml"
  when:
    - groups['rabbitmq'][0] == inventory_hostname

- import_tasks: "cookie-setup/nodes.yml"
  when:
    - groups['rabbitmq'][0] != inventory_hostname