---
- name: 重新启动chronyd服务
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: 重新启动systemd-journald服务
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes 

