---

- name: 创建目录
  file:
    path: "{{ k8s_dir }}/kube-scheduler"
    state: directory

- name: 生成证书
  shell: "/opt/k8s/bin/cfssl gencert -ca=/opt/k8s/work/ca.pem -ca-key=/opt/k8s/work/ca-key.pem -config=/opt/k8s/work/ca-config.json -profile=kubernetes kube-scheduler-csr.json | /opt/k8s/bin/cfssljson -bare kube-scheduler"
  args:
    chdir: /opt/k8s/work/
    creates: kube-scheduler.pem
#  ignore_errors: true
  when: 'inventory_hostname == groups.master[0]'

- name: 分发生成的证书和私钥
  copy:
    src: "/opt/k8s/work/{{ item }}"
    dest: "/etc/kubernetes/cert/{{ item }}"
  with_list:
    - kube-scheduler.pem
    - kube-scheduler-key.pem
  notify:
    - 重新启动kube-scheduler.service服务

- name: 生成kube-scheduler.kubeconfig文件 - 1
  shell: "/opt/k8s/bin/kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/cert/ca.pem --embed-certs=true --server=https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:6443 --kubeconfig=kube-scheduler.kubeconfig"
  args:
    chdir: /etc/kubernetes/

- name: 生成kube-scheduler.kubeconfig文件 - 2
  shell: "/opt/k8s/bin/kubectl config set-credentials system:kube-scheduler --client-certificate=/etc/kubernetes/cert/kube-scheduler.pem --client-key=/etc/kubernetes/cert/kube-scheduler-key.pem --embed-certs=true --kubeconfig=kube-scheduler.kubeconfig"
  args:
    chdir: /etc/kubernetes/

- name: 生成kube-scheduler.kubeconfig文件 - 3
  shell: "/opt/k8s/bin/kubectl config set-context system:kube-scheduler --cluster=kubernetes --user=system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig"
  args:
    chdir: /etc/kubernetes/

- name: 设置默认上下文
  shell: "/opt/k8s/bin/kubectl config use-context system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig"
  args:
    chdir: /etc/kubernetes/

- name: 分发kube-scheduler.yaml配置文件
  copy:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/kube-scheduler.yaml
  notify:
    - 重新启动kube-scheduler.service服务

- name: 分发kube-scheduler.service文件
  template: 
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
  notify:
    - 重新启动kube-scheduler.service服务






