---

# - name: 安装docker
#   yum:
#     - docker-ce-18.09.9
#     - docker-ce-cli-18.09.9
#     - containerd.io

- name: 分发docker二进制文件
  copy:
    src: "{{ k8s_deploy_path }}/bin/docker/"
    dest: /opt/k8s/bin/
    mode: '0755'

- name: 分发docker.service文件
  template: 
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service

- name: 创建配置文件目录
  file:
    path: "{{ item }}"
    state: directory
  with_list:
    - /etc/docker
    - "{{ docker_data_dir }}"

- name: 分发daemon.json配置文件
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - 重新启动docker服务

- name: 强制执行handlers重启docker
  meta: flush_handlers

- name: 安装docker python sdk
  pip:
    name: docker

- name: 登录nexus docker group镜像仓库
  docker_login:
    registry: 192.168.0.120:8083
    username: admin
    password: admin123
    reauthorize: yes