rabbitmq:
  version: 3.7.10
  use_longname: true
  user: rabbitmq
  group: rabbitmq
  ulimit_open_files: 65535
  logrotate_period: weekly
  logrotate_number: 10
  port: 5672
  cluster:
    is_clustered: false
    cookie: 
  custom_configurations: [{"name":"num_acceptors.tcp","value":"10"}]
  plugins: ["rabbitmq_management"]
  policies: []

  